"""Public interface for the Bagger-SPL simulation core."""

from .acoustics.hybrid import (
    HybridBoxSolver,
    HybridFieldSnapshot,
    HybridSolverResult,
    HybridSolverSummary,
)
from .acoustics.sealed import SealedAlignmentSummary, SealedBoxResponse, SealedBoxSolver
from .acoustics.vented import VentedAlignmentSummary, VentedBoxResponse, VentedBoxSolver
from .calibration import (
    DEFAULT_CALIBRATION_PRIOR,
    CalibrationOverrides,
    CalibrationParameter,
    CalibrationPrior,
    CalibrationUpdate,
    ParameterPrior,
    apply_calibration_overrides_to_box,
    apply_calibration_overrides_to_drive_voltage,
    derive_calibration_overrides,
    derive_calibration_update,
)
from .drivers import (
    DEFAULT_DRIVER,
    BoxDesign,
    DriverParameters,
    PortGeometry,
    VentedBoxDesign,
    recommended_vented_alignment,
)
from .measurements import (
    MeasurementDelta,
    MeasurementDiagnosis,
    MeasurementStats,
    MeasurementTrace,
    compare_measurement_to_prediction,
    measurement_from_response,
    parse_klippel_dat,
    parse_rew_mdat,
)
from .serialization import (
    dataclass_schema,
    hybrid_simulation_request_schema,
    hybrid_simulation_response_schema,
    hybrid_simulation_schema,
    sealed_simulation_request_schema,
    sealed_simulation_response_schema,
    sealed_simulation_schema,
    solver_json_schemas,
    vented_simulation_request_schema,
    vented_simulation_response_schema,
    vented_simulation_schema,
)
from .tolerances import (
    DEFAULT_TOLERANCES,
    MetricStats,
    ToleranceReport,
    ToleranceSpec,
    run_tolerance_analysis,
)

__all__ = [
    "DriverParameters",
    "BoxDesign",
    "PortGeometry",
    "VentedBoxDesign",
    "DEFAULT_DRIVER",
    "recommended_vented_alignment",
    "SealedBoxSolver",
    "SealedBoxResponse",
    "SealedAlignmentSummary",
    "VentedBoxSolver",
    "VentedBoxResponse",
    "VentedAlignmentSummary",
    "HybridBoxSolver",
    "HybridSolverResult",
    "HybridSolverSummary",
    "HybridFieldSnapshot",
    "dataclass_schema",
    "hybrid_simulation_request_schema",
    "hybrid_simulation_response_schema",
    "hybrid_simulation_schema",
    "sealed_simulation_request_schema",
    "sealed_simulation_response_schema",
    "sealed_simulation_schema",
    "vented_simulation_request_schema",
    "vented_simulation_response_schema",
    "vented_simulation_schema",
    "solver_json_schemas",
    "ToleranceSpec",
    "ToleranceReport",
    "MetricStats",
    "DEFAULT_TOLERANCES",
    "run_tolerance_analysis",
    "MeasurementTrace",
    "MeasurementDelta",
    "MeasurementStats",
    "MeasurementDiagnosis",
    "parse_klippel_dat",
    "parse_rew_mdat",
    "measurement_from_response",
    "compare_measurement_to_prediction",
    "ParameterPrior",
    "CalibrationParameter",
    "CalibrationPrior",
    "CalibrationOverrides",
    "CalibrationUpdate",
    "DEFAULT_CALIBRATION_PRIOR",
    "apply_calibration_overrides_to_box",
    "apply_calibration_overrides_to_drive_voltage",
    "derive_calibration_overrides",
    "derive_calibration_update",
]
